// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ts/tspb/monitor.proto

/*
	Package tspb is a generated protocol buffer package.

	It is generated from these files:
		ts/tspb/monitor.proto
		ts/tspb/timeseries.proto

	It has these top-level messages:
		RollupDatapoint
		MetricRollups
		NodeRollupDatapoint
		TimeSeriesDatapoint
		TimeSeriesData
		Query
		TimeSeriesQueryRequest
		TimeSeriesQueryResponse
		DumpRequest
*/
package tspb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import sortkeys "github.com/gogo/protobuf/sortkeys"
import binary "encoding/binary"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type RollupRes int32

const (
	RollupRes_oneM RollupRes = 0
	RollupRes_tenM RollupRes = 1
	RollupRes_oneH RollupRes = 2
	RollupRes_oneD RollupRes = 3
)

var RollupRes_name = map[int32]string{
	0: "oneM",
	1: "tenM",
	2: "oneH",
	3: "oneD",
}
var RollupRes_value = map[string]int32{
	"oneM": 0,
	"tenM": 1,
	"oneH": 2,
	"oneD": 3,
}

func (x RollupRes) String() string {
	return proto.EnumName(RollupRes_name, int32(x))
}
func (RollupRes) EnumDescriptor() ([]byte, []int) { return fileDescriptorMonitor, []int{0} }

type RollupDatapoint struct {
	TimestampNanos int64   `protobuf:"varint,1,opt,name=timestampNanos,proto3" json:"timestampNanos,omitempty"`
	First          float64 `protobuf:"fixed64,2,opt,name=first,proto3" json:"first,omitempty"`
	Last           float64 `protobuf:"fixed64,3,opt,name=last,proto3" json:"last,omitempty"`
	Min            float64 `protobuf:"fixed64,4,opt,name=min,proto3" json:"min,omitempty"`
	Max            float64 `protobuf:"fixed64,5,opt,name=max,proto3" json:"max,omitempty"`
	Sum            float64 `protobuf:"fixed64,6,opt,name=sum,proto3" json:"sum,omitempty"`
	Count          uint32  `protobuf:"varint,7,opt,name=count,proto3" json:"count,omitempty"`
	Variance       float64 `protobuf:"fixed64,8,opt,name=variance,proto3" json:"variance,omitempty"`
}

func (m *RollupDatapoint) Reset()                    { *m = RollupDatapoint{} }
func (m *RollupDatapoint) String() string            { return proto.CompactTextString(m) }
func (*RollupDatapoint) ProtoMessage()               {}
func (*RollupDatapoint) Descriptor() ([]byte, []int) { return fileDescriptorMonitor, []int{0} }

type MetricRollups struct {
	MostRecent map[int32]*RollupDatapoint `protobuf:"bytes,1,rep,name=mostRecent" json:"mostRecent,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MetricRollups) Reset()                    { *m = MetricRollups{} }
func (m *MetricRollups) String() string            { return proto.CompactTextString(m) }
func (*MetricRollups) ProtoMessage()               {}
func (*MetricRollups) Descriptor() ([]byte, []int) { return fileDescriptorMonitor, []int{1} }

type NodeRollupDatapoint struct {
	NodeID string           `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Rollup *RollupDatapoint `protobuf:"bytes,2,opt,name=rollup" json:"rollup,omitempty"`
}

func (m *NodeRollupDatapoint) Reset()                    { *m = NodeRollupDatapoint{} }
func (m *NodeRollupDatapoint) String() string            { return proto.CompactTextString(m) }
func (*NodeRollupDatapoint) ProtoMessage()               {}
func (*NodeRollupDatapoint) Descriptor() ([]byte, []int) { return fileDescriptorMonitor, []int{2} }

func init() {
	proto.RegisterType((*RollupDatapoint)(nil), "tspb.RollupDatapoint")
	proto.RegisterType((*MetricRollups)(nil), "tspb.MetricRollups")
	proto.RegisterType((*NodeRollupDatapoint)(nil), "tspb.NodeRollupDatapoint")
	proto.RegisterEnum("tspb.RollupRes", RollupRes_name, RollupRes_value)
}
func (m *RollupDatapoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RollupDatapoint) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.TimestampNanos != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMonitor(dAtA, i, uint64(m.TimestampNanos))
	}
	if m.First != 0 {
		dAtA[i] = 0x11
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.First))))
		i += 8
	}
	if m.Last != 0 {
		dAtA[i] = 0x19
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Last))))
		i += 8
	}
	if m.Min != 0 {
		dAtA[i] = 0x21
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Min))))
		i += 8
	}
	if m.Max != 0 {
		dAtA[i] = 0x29
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Max))))
		i += 8
	}
	if m.Sum != 0 {
		dAtA[i] = 0x31
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Sum))))
		i += 8
	}
	if m.Count != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintMonitor(dAtA, i, uint64(m.Count))
	}
	if m.Variance != 0 {
		dAtA[i] = 0x41
		i++
		binary.LittleEndian.PutUint64(dAtA[i:], uint64(math.Float64bits(float64(m.Variance))))
		i += 8
	}
	return i, nil
}

func (m *MetricRollups) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetricRollups) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.MostRecent) > 0 {
		keysForMostRecent := make([]int32, 0, len(m.MostRecent))
		for k := range m.MostRecent {
			keysForMostRecent = append(keysForMostRecent, int32(k))
		}
		sortkeys.Int32s(keysForMostRecent)
		for _, k := range keysForMostRecent {
			dAtA[i] = 0xa
			i++
			v := m.MostRecent[int32(k)]
			msgSize := 0
			if v != nil {
				msgSize = v.Size()
				msgSize += 1 + sovMonitor(uint64(msgSize))
			}
			mapSize := 1 + sovMonitor(uint64(k)) + msgSize
			i = encodeVarintMonitor(dAtA, i, uint64(mapSize))
			dAtA[i] = 0x8
			i++
			i = encodeVarintMonitor(dAtA, i, uint64(k))
			if v != nil {
				dAtA[i] = 0x12
				i++
				i = encodeVarintMonitor(dAtA, i, uint64(v.Size()))
				n1, err := v.MarshalTo(dAtA[i:])
				if err != nil {
					return 0, err
				}
				i += n1
			}
		}
	}
	return i, nil
}

func (m *NodeRollupDatapoint) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeRollupDatapoint) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.NodeID) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintMonitor(dAtA, i, uint64(len(m.NodeID)))
		i += copy(dAtA[i:], m.NodeID)
	}
	if m.Rollup != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMonitor(dAtA, i, uint64(m.Rollup.Size()))
		n2, err := m.Rollup.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	return i, nil
}

func encodeVarintMonitor(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RollupDatapoint) Size() (n int) {
	var l int
	_ = l
	if m.TimestampNanos != 0 {
		n += 1 + sovMonitor(uint64(m.TimestampNanos))
	}
	if m.First != 0 {
		n += 9
	}
	if m.Last != 0 {
		n += 9
	}
	if m.Min != 0 {
		n += 9
	}
	if m.Max != 0 {
		n += 9
	}
	if m.Sum != 0 {
		n += 9
	}
	if m.Count != 0 {
		n += 1 + sovMonitor(uint64(m.Count))
	}
	if m.Variance != 0 {
		n += 9
	}
	return n
}

func (m *MetricRollups) Size() (n int) {
	var l int
	_ = l
	if len(m.MostRecent) > 0 {
		for k, v := range m.MostRecent {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovMonitor(uint64(l))
			}
			mapEntrySize := 1 + sovMonitor(uint64(k)) + l
			n += mapEntrySize + 1 + sovMonitor(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *NodeRollupDatapoint) Size() (n int) {
	var l int
	_ = l
	l = len(m.NodeID)
	if l > 0 {
		n += 1 + l + sovMonitor(uint64(l))
	}
	if m.Rollup != nil {
		l = m.Rollup.Size()
		n += 1 + l + sovMonitor(uint64(l))
	}
	return n
}

func sovMonitor(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMonitor(x uint64) (n int) {
	return sovMonitor(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RollupDatapoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonitor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RollupDatapoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RollupDatapoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimestampNanos", wireType)
			}
			m.TimestampNanos = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimestampNanos |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field First", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.First = float64(math.Float64frombits(v))
		case 3:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Last", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Last = float64(math.Float64frombits(v))
		case 4:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Min", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Min = float64(math.Float64frombits(v))
		case 5:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Max", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Max = float64(math.Float64frombits(v))
		case 6:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sum", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Sum = float64(math.Float64frombits(v))
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Variance", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v = uint64(binary.LittleEndian.Uint64(dAtA[iNdEx:]))
			iNdEx += 8
			m.Variance = float64(math.Float64frombits(v))
		default:
			iNdEx = preIndex
			skippy, err := skipMonitor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMonitor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetricRollups) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonitor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetricRollups: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetricRollups: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MostRecent", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonitor
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.MostRecent == nil {
				m.MostRecent = make(map[int32]*RollupDatapoint)
			}
			var mapkey int32
			var mapvalue *RollupDatapoint
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMonitor
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMonitor
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapkey |= (int32(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMonitor
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= (int(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthMonitor
					}
					postmsgIndex := iNdEx + mapmsglen
					if mapmsglen < 0 {
						return ErrInvalidLengthMonitor
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &RollupDatapoint{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMonitor(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthMonitor
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.MostRecent[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonitor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMonitor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeRollupDatapoint) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMonitor
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeRollupDatapoint: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeRollupDatapoint: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthMonitor
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Rollup", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMonitor
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Rollup == nil {
				m.Rollup = &RollupDatapoint{}
			}
			if err := m.Rollup.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipMonitor(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMonitor
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMonitor(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMonitor
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMonitor
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMonitor
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMonitor
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMonitor(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMonitor = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMonitor   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("ts/tspb/monitor.proto", fileDescriptorMonitor) }

var fileDescriptorMonitor = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x8b, 0xd4, 0x30,
	0x18, 0xc6, 0x27, 0xd3, 0x3f, 0xce, 0xbe, 0xcb, 0xba, 0x25, 0xba, 0x12, 0xf6, 0x50, 0xca, 0x08,
	0x52, 0x14, 0xbb, 0xb0, 0x7b, 0x11, 0x8f, 0x3a, 0x82, 0x1e, 0x3a, 0x87, 0xe0, 0xd1, 0x4b, 0xa6,
	0x13, 0xa1, 0xd8, 0x26, 0xa5, 0x79, 0x3b, 0xcc, 0x7c, 0x0b, 0x3f, 0x87, 0x9f, 0x64, 0xc0, 0x8b,
	0x47, 0x8f, 0x5a, 0xbf, 0x88, 0x24, 0x2d, 0x83, 0xf6, 0xb0, 0xb7, 0xe7, 0xf9, 0xe5, 0x69, 0xde,
	0xbe, 0x0f, 0x81, 0x2b, 0x34, 0x37, 0x68, 0x9a, 0xcd, 0x4d, 0xad, 0x55, 0x89, 0xba, 0xcd, 0x9a,
	0x56, 0xa3, 0xa6, 0xbe, 0x65, 0xcb, 0xef, 0x04, 0x2e, 0xb9, 0xae, 0xaa, 0xae, 0x59, 0x09, 0x14,
	0x8d, 0x2e, 0x15, 0xd2, 0x67, 0xf0, 0x10, 0xcb, 0x5a, 0x1a, 0x14, 0x75, 0xb3, 0x16, 0x4a, 0x1b,
	0x46, 0x12, 0x92, 0x7a, 0x7c, 0x42, 0xe9, 0x63, 0x08, 0x3e, 0x97, 0xad, 0x41, 0x36, 0x4f, 0x48,
	0x4a, 0xf8, 0x60, 0x28, 0x05, 0xbf, 0x12, 0x06, 0x99, 0xe7, 0xa0, 0xd3, 0x34, 0x02, 0xaf, 0x2e,
	0x15, 0xf3, 0x1d, 0xb2, 0xd2, 0x11, 0xb1, 0x67, 0xc1, 0x48, 0xc4, 0xde, 0x12, 0xd3, 0xd5, 0x2c,
	0x1c, 0x88, 0xe9, 0x6a, 0x7b, 0x7f, 0xa1, 0x3b, 0x85, 0xec, 0x41, 0x42, 0xd2, 0x0b, 0x3e, 0x18,
	0x7a, 0x0d, 0x8b, 0x9d, 0x68, 0x4b, 0xa1, 0x0a, 0xc9, 0x16, 0x2e, 0x7c, 0xf2, 0xcb, 0x6f, 0x04,
	0x2e, 0x72, 0x89, 0x6d, 0x59, 0x0c, 0x3b, 0x19, 0xfa, 0x16, 0xa0, 0xd6, 0x06, 0xb9, 0x2c, 0xa4,
	0x42, 0x46, 0x12, 0x2f, 0x3d, 0xbf, 0x7d, 0x9a, 0xd9, 0xd5, 0xb3, 0xff, 0x82, 0x59, 0x7e, 0x4a,
	0xbd, 0x53, 0xd8, 0x1e, 0xf8, 0x3f, 0x9f, 0x5d, 0x7f, 0x84, 0xcb, 0xc9, 0xb1, 0xfd, 0xdb, 0x2f,
	0xf2, 0xe0, 0x8a, 0x09, 0xb8, 0x95, 0xf4, 0x05, 0x04, 0x3b, 0x51, 0x75, 0xd2, 0xb5, 0x71, 0x7e,
	0x7b, 0x35, 0x0c, 0x99, 0x74, 0xcb, 0x87, 0xcc, 0xeb, 0xf9, 0x2b, 0xb2, 0xfc, 0x04, 0x8f, 0xd6,
	0x7a, 0x2b, 0xa7, 0xed, 0x3f, 0x81, 0x50, 0xe9, 0xad, 0xfc, 0xb0, 0x72, 0x97, 0x9f, 0xf1, 0xd1,
	0xd1, 0x97, 0x10, 0xb6, 0x2e, 0x7a, 0xff, 0x80, 0x31, 0xf4, 0xfc, 0x0e, 0xce, 0x86, 0x23, 0x2e,
	0x0d, 0x5d, 0x80, 0xaf, 0x95, 0xcc, 0xa3, 0x99, 0x55, 0x28, 0x55, 0x1e, 0x91, 0x91, 0xbd, 0x8f,
	0xe6, 0xa3, 0x5a, 0x45, 0xde, 0x1b, 0x76, 0xfc, 0x1d, 0xcf, 0x8e, 0x7d, 0x4c, 0x7e, 0xf4, 0x31,
	0xf9, 0xd9, 0xc7, 0xe4, 0x57, 0x1f, 0x93, 0xaf, 0x7f, 0xe2, 0xd9, 0x26, 0x74, 0x8f, 0xe6, 0xee,
	0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x8d, 0xcd, 0xa6, 0x4d, 0x02, 0x00, 0x00,
}
